// Mocks generated by Mockito 5.4.6 from annotations
// in darshan_app/test/features/call/presentation/call_ui_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:darshan_app/core/error/failure.dart' as _i6;
import 'package:darshan_app/core/usecase/success.dart' as _i7;
import 'package:darshan_app/features/call/domain/entities/call_event.dart'
    as _i15;
import 'package:darshan_app/features/call/domain/entities/consumer_entity.dart'
    as _i12;
import 'package:darshan_app/features/call/domain/entities/local_media_entity.dart'
    as _i8;
import 'package:darshan_app/features/call/domain/entities/media_kind.dart'
    as _i17;
import 'package:darshan_app/features/call/domain/entities/producer_entity.dart'
    as _i14;
import 'package:darshan_app/features/call/domain/entities/room_entity.dart'
    as _i16;
import 'package:darshan_app/features/call/domain/repositories/call_repository.dart'
    as _i2;
import 'package:darshan_app/features/call/domain/usecases/consume_media_usecase.dart'
    as _i11;
import 'package:darshan_app/features/call/domain/usecases/init_local_media_usecase.dart'
    as _i3;
import 'package:darshan_app/features/call/domain/usecases/produce_media_usecase.dart'
    as _i13;
import 'package:darshan_app/features/call/domain/usecases/switch_camera_usecase.dart'
    as _i10;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i18;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCallRepository_0 extends _i1.SmartFake
    implements _i2.CallRepository {
  _FakeCallRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InitLocalMediaUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitLocalMediaUsecase extends _i1.Mock
    implements _i3.InitLocalMediaUsecase {
  MockInitLocalMediaUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>> call(
    _i3.InitLocalMediaParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
          >);
}

/// A class which mocks [SwitchCameraUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchCameraUsecase extends _i1.Mock
    implements _i10.SwitchCameraUsecase {
  MockSwitchCameraUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>> call(
    _i10.SwitchCameraParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
          >);
}

/// A class which mocks [ConsumeMediaUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsumeMediaUsecase extends _i1.Mock
    implements _i11.ConsumeMediaUsecase {
  MockConsumeMediaUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>> call(
    _i11.ConsumeMediaParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
          >);
}

/// A class which mocks [ProduceMediaUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProduceMediaUsecase extends _i1.Mock
    implements _i13.ProduceMediaUsecase {
  MockProduceMediaUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>> call(
    _i13.ProduceMediaParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
          >);
}

/// A class which mocks [CallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRepository extends _i1.Mock implements _i2.CallRepository {
  MockCallRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i15.CallEvent> get onCallEvent =>
      (super.noSuchMethod(
            Invocation.getter(#onCallEvent),
            returnValue: _i4.Stream<_i15.CallEvent>.empty(),
          )
          as _i4.Stream<_i15.CallEvent>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>> createRoom({
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [], {#displayName: displayName}),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>
                  >(
                    this,
                    Invocation.method(#createRoom, [], {
                      #displayName: displayName,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>> joinRoom({
    required String? roomId,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [], {
              #roomId: roomId,
              #displayName: displayName,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>
                  >(
                    this,
                    Invocation.method(#joinRoom, [], {
                      #roomId: roomId,
                      #displayName: displayName,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i16.RoomEntity>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>> leaveRoom({
    required String? roomId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [], {
              #roomId: roomId,
              #peerId: peerId,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Success<void>>>(
                    this,
                    Invocation.method(#leaveRoom, [], {
                      #roomId: roomId,
                      #peerId: peerId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>>
  produce({
    required String? roomId,
    required _i17.MediaKind? kind,
    required _i18.MediaStreamTrack? track,
    required _i18.MediaStream? stream,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#produce, [], {
              #roomId: roomId,
              #kind: kind,
              #track: track,
              #stream: stream,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
                  >(
                    this,
                    Invocation.method(#produce, [], {
                      #roomId: roomId,
                      #kind: kind,
                      #track: track,
                      #stream: stream,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i14.ProducerEntity>>
          >);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>>
  consume({
    required String? roomId,
    required String? producerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consume, [], {
              #roomId: roomId,
              #producerId: producerId,
              #peerId: peerId,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
                  >(
                    this,
                    Invocation.method(#consume, [], {
                      #roomId: roomId,
                      #producerId: producerId,
                      #peerId: peerId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i12.ConsumerEntity>>
          >);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>> toggleAudio({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAudio, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Success<void>>>(
                    this,
                    Invocation.method(#toggleAudio, [], {
                      #producerId: producerId,
                      #pause: pause,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>> toggleCamera({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCamera, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Success<void>>>(
                    this,
                    Invocation.method(#toggleCamera, [], {
                      #producerId: producerId,
                      #pause: pause,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<void>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>>
  switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                  >(this, Invocation.method(#switchCamera, [])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
          >);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>>
  initLocalMedia({required bool? enableAudio, required bool? enableVideo}) =>
      (super.noSuchMethod(
            Invocation.method(#initLocalMedia, [], {
              #enableAudio: enableAudio,
              #enableVideo: enableVideo,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
                  >(
                    this,
                    Invocation.method(#initLocalMedia, [], {
                      #enableAudio: enableAudio,
                      #enableVideo: enableVideo,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, _i7.Success<_i8.LocalMediaEntity>>
          >);
}
