// Mocks generated by Mockito 5.4.6 from annotations
// in darshan_app/test/features/call/presentation/call_fetcher_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:darshan_app/core/error/failure.dart' as _i6;
import 'package:darshan_app/core/usecase/success.dart' as _i7;
import 'package:darshan_app/features/call/domain/entities/room_entity.dart'
    as _i8;
import 'package:darshan_app/features/call/domain/repositories/call_repository.dart'
    as _i2;
import 'package:darshan_app/features/call/domain/usecases/create_room_usecase.dart'
    as _i3;
import 'package:darshan_app/features/call/domain/usecases/join_room_usecase.dart'
    as _i10;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCallRepository_0 extends _i1.SmartFake
    implements _i2.CallRepository {
  _FakeCallRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateRoomUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateRoomUsecase extends _i1.Mock implements _i3.CreateRoomUsecase {
  MockCreateRoomUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>> call(
    _i3.CreateRoomParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>>);
}

/// A class which mocks [JoinRoomUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJoinRoomUsecase extends _i1.Mock implements _i10.JoinRoomUsecase {
  MockJoinRoomUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CallRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCallRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CallRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>> call(
    _i10.JoinRoomParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>
                >.value(
                  _i9.dummyValue<
                    _i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Success<_i8.RoomEntity>>>);
}
