// Mocks generated by Mockito 5.4.6 from annotations
// in darshan_app/test/features/call/domain/usecases/extended_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:webrtc_interface/src/media_stream_track.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMediaStreamTrack_0 extends _i1.SmartFake
    implements _i2.MediaStreamTrack {
  _FakeMediaStreamTrack_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaStreamTrack].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStreamTrack extends _i1.Mock implements _i2.MediaStreamTrack {
  MockMediaStreamTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);

  @override
  set onMute(_i2.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onUnMute(_i2.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onUnMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onEnded(_i2.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onEnded, value),
    returnValueForMissingStub: null,
  );

  @override
  set enabled(bool? b) => super.noSuchMethod(
    Invocation.setter(#enabled, b),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getConstraints() =>
      (super.noSuchMethod(
            Invocation.method(#getConstraints, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<void> applyConstraints([Map<String, dynamic>? constraints]) =>
      (super.noSuchMethod(
            Invocation.method(#applyConstraints, [constraints]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.MediaStreamTrack> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i3.Future<_i2.MediaStreamTrack>.value(
              _FakeMediaStreamTrack_0(this, Invocation.method(#clone, [])),
            ),
          )
          as _i3.Future<_i2.MediaStreamTrack>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  Map<String, dynamic> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<bool> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> adaptRes(int? width, int? height) =>
      (super.noSuchMethod(
            Invocation.method(#adaptRes, [width, height]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void enableSpeakerphone(bool? enable) => super.noSuchMethod(
    Invocation.method(#enableSpeakerphone, [enable]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.ByteBuffer> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i3.Future<_i4.ByteBuffer>.value(
              _i5.dummyValue<_i4.ByteBuffer>(
                this,
                Invocation.method(#captureFrame, []),
              ),
            ),
          )
          as _i3.Future<_i4.ByteBuffer>);

  @override
  _i3.Future<bool> hasTorch() =>
      (super.noSuchMethod(
            Invocation.method(#hasTorch, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setTorch(bool? torch) =>
      (super.noSuchMethod(
            Invocation.method(#setTorch, [torch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
