// Mocks generated by Mockito 5.4.6 from annotations
// in darshan_app/test/features/call/domain/usecases/usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:darshan_app/core/error/failure.dart' as _i5;
import 'package:darshan_app/core/usecase/success.dart' as _i6;
import 'package:darshan_app/features/call/domain/entities/consumer_entity.dart'
    as _i12;
import 'package:darshan_app/features/call/domain/entities/local_media_entity.dart'
    as _i13;
import 'package:darshan_app/features/call/domain/entities/media_kind.dart'
    as _i10;
import 'package:darshan_app/features/call/domain/entities/producer_entity.dart'
    as _i9;
import 'package:darshan_app/features/call/domain/entities/room_entity.dart'
    as _i7;
import 'package:darshan_app/features/call/domain/repositories/call_repository.dart'
    as _i2;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i11;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRepository extends _i1.Mock implements _i2.CallRepository {
  MockCallRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>> createRoom({
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [], {#displayName: displayName}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>
                  >(
                    this,
                    Invocation.method(#createRoom, [], {
                      #displayName: displayName,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>> joinRoom({
    required String? roomId,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [], {
              #roomId: roomId,
              #displayName: displayName,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>
                  >(
                    this,
                    Invocation.method(#joinRoom, [], {
                      #roomId: roomId,
                      #displayName: displayName,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i7.RoomEntity>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>> leaveRoom({
    required String? roomId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [], {
              #roomId: roomId,
              #peerId: peerId,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.Success<void>>>(
                    this,
                    Invocation.method(#leaveRoom, [], {
                      #roomId: roomId,
                      #peerId: peerId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i9.ProducerEntity>>> produce({
    required String? roomId,
    required _i10.MediaKind? kind,
    required _i11.MediaStreamTrack? track,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#produce, [], {
              #roomId: roomId,
              #kind: kind,
              #track: track,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i9.ProducerEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i9.ProducerEntity>>
                  >(
                    this,
                    Invocation.method(#produce, [], {
                      #roomId: roomId,
                      #kind: kind,
                      #track: track,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, _i6.Success<_i9.ProducerEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i12.ConsumerEntity>>>
  consume({
    required String? roomId,
    required String? producerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consume, [], {
              #roomId: roomId,
              #producerId: producerId,
              #peerId: peerId,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i12.ConsumerEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i12.ConsumerEntity>>
                  >(
                    this,
                    Invocation.method(#consume, [], {
                      #roomId: roomId,
                      #producerId: producerId,
                      #peerId: peerId,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, _i6.Success<_i12.ConsumerEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>> toggleAudio({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAudio, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.Success<void>>>(
                    this,
                    Invocation.method(#toggleAudio, [], {
                      #producerId: producerId,
                      #pause: pause,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>> toggleCamera({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCamera, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.Success<void>>>(
                    this,
                    Invocation.method(#toggleCamera, [], {
                      #producerId: producerId,
                      #pause: pause,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.Success<void>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>>
  switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
                  >(this, Invocation.method(#switchCamera, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>>
  initLocalMedia({required bool? enableAudio, required bool? enableVideo}) =>
      (super.noSuchMethod(
            Invocation.method(#initLocalMedia, [], {
              #enableAudio: enableAudio,
              #enableVideo: enableVideo,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
                  >(
                    this,
                    Invocation.method(#initLocalMedia, [], {
                      #enableAudio: enableAudio,
                      #enableVideo: enableVideo,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, _i6.Success<_i13.LocalMediaEntity>>
          >);
}
