// Mocks generated by Mockito 5.4.6 from annotations
// in darshan_app/test/features/call/data/repositories/call_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i12;

import 'package:darshan_app/core/network/network_info.dart' as _i11;
import 'package:darshan_app/features/call/data/datasources/call_remote_data_source.dart'
    as _i7;
import 'package:darshan_app/features/call/data/datasources/media_data_source.dart'
    as _i10;
import 'package:darshan_app/features/call/data/models/consumer_model.dart'
    as _i4;
import 'package:darshan_app/features/call/data/models/producer_model.dart'
    as _i3;
import 'package:darshan_app/features/call/data/models/room_model.dart' as _i2;
import 'package:darshan_app/features/call/domain/entities/local_media_entity.dart'
    as _i5;
import 'package:darshan_app/features/call/domain/entities/media_kind.dart'
    as _i9;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoomModel_0 extends _i1.SmartFake implements _i2.RoomModel {
  _FakeRoomModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProducerModel_1 extends _i1.SmartFake implements _i3.ProducerModel {
  _FakeProducerModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConsumerModel_2 extends _i1.SmartFake implements _i4.ConsumerModel {
  _FakeConsumerModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalMediaEntity_3 extends _i1.SmartFake
    implements _i5.LocalMediaEntity {
  _FakeLocalMediaEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaStreamTrack_4 extends _i1.SmartFake
    implements _i6.MediaStreamTrack {
  _FakeMediaStreamTrack_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaStream_5 extends _i1.SmartFake implements _i6.MediaStream {
  _FakeMediaStream_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CallRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRemoteDataSource extends _i1.Mock
    implements _i7.CallRemoteDataSource {
  MockCallRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<Map<String, dynamic>> get onEvent =>
      (super.noSuchMethod(
            Invocation.getter(#onEvent),
            returnValue: _i8.Stream<Map<String, dynamic>>.empty(),
          )
          as _i8.Stream<Map<String, dynamic>>);

  @override
  _i8.Future<_i2.RoomModel> createRoom(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [displayName]),
            returnValue: _i8.Future<_i2.RoomModel>.value(
              _FakeRoomModel_0(
                this,
                Invocation.method(#createRoom, [displayName]),
              ),
            ),
          )
          as _i8.Future<_i2.RoomModel>);

  @override
  _i8.Future<_i2.RoomModel> joinRoom(String? roomId, String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [roomId, displayName]),
            returnValue: _i8.Future<_i2.RoomModel>.value(
              _FakeRoomModel_0(
                this,
                Invocation.method(#joinRoom, [roomId, displayName]),
              ),
            ),
          )
          as _i8.Future<_i2.RoomModel>);

  @override
  _i8.Future<void> leaveRoom(String? roomId, String? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [roomId, peerId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.ProducerModel> produce({
    required String? roomId,
    required _i9.MediaKind? kind,
    required _i6.MediaStreamTrack? track,
    required _i6.MediaStream? stream,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#produce, [], {
              #roomId: roomId,
              #kind: kind,
              #track: track,
              #stream: stream,
            }),
            returnValue: _i8.Future<_i3.ProducerModel>.value(
              _FakeProducerModel_1(
                this,
                Invocation.method(#produce, [], {
                  #roomId: roomId,
                  #kind: kind,
                  #track: track,
                  #stream: stream,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.ProducerModel>);

  @override
  _i8.Future<_i4.ConsumerModel> consume({
    required String? roomId,
    required String? producerId,
    required String? peerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consume, [], {
              #roomId: roomId,
              #producerId: producerId,
              #peerId: peerId,
            }),
            returnValue: _i8.Future<_i4.ConsumerModel>.value(
              _FakeConsumerModel_2(
                this,
                Invocation.method(#consume, [], {
                  #roomId: roomId,
                  #producerId: producerId,
                  #peerId: peerId,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.ConsumerModel>);

  @override
  _i8.Future<void> toggleAudio({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAudio, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleCamera({
    required String? producerId,
    required bool? pause,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCamera, [], {
              #producerId: producerId,
              #pause: pause,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [MediaDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaDataSource extends _i1.Mock implements _i10.MediaDataSource {
  MockMediaDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.LocalMediaEntity> getUserMedia({
    required bool? enableAudio,
    required bool? enableVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMedia, [], {
              #enableAudio: enableAudio,
              #enableVideo: enableVideo,
            }),
            returnValue: _i8.Future<_i5.LocalMediaEntity>.value(
              _FakeLocalMediaEntity_3(
                this,
                Invocation.method(#getUserMedia, [], {
                  #enableAudio: enableAudio,
                  #enableVideo: enableVideo,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.LocalMediaEntity>);

  @override
  _i8.Future<List<_i6.MediaDeviceInfo>> enumerateDevices() =>
      (super.noSuchMethod(
            Invocation.method(#enumerateDevices, []),
            returnValue: _i8.Future<List<_i6.MediaDeviceInfo>>.value(
              <_i6.MediaDeviceInfo>[],
            ),
          )
          as _i8.Future<List<_i6.MediaDeviceInfo>>);

  @override
  _i8.Future<_i5.LocalMediaEntity> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i8.Future<_i5.LocalMediaEntity>.value(
              _FakeLocalMediaEntity_3(
                this,
                Invocation.method(#switchCamera, []),
              ),
            ),
          )
          as _i8.Future<_i5.LocalMediaEntity>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [MediaStreamTrack].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStreamTrack extends _i1.Mock implements _i6.MediaStreamTrack {
  MockMediaStreamTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);

  @override
  set onMute(_i6.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onUnMute(_i6.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onUnMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onEnded(_i6.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onEnded, value),
    returnValueForMissingStub: null,
  );

  @override
  set enabled(bool? b) => super.noSuchMethod(
    Invocation.setter(#enabled, b),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getConstraints() =>
      (super.noSuchMethod(
            Invocation.method(#getConstraints, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<void> applyConstraints([Map<String, dynamic>? constraints]) =>
      (super.noSuchMethod(
            Invocation.method(#applyConstraints, [constraints]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.MediaStreamTrack> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i8.Future<_i6.MediaStreamTrack>.value(
              _FakeMediaStreamTrack_4(this, Invocation.method(#clone, [])),
            ),
          )
          as _i8.Future<_i6.MediaStreamTrack>);

  @override
  _i8.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, dynamic> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<bool> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> adaptRes(int? width, int? height) =>
      (super.noSuchMethod(
            Invocation.method(#adaptRes, [width, height]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void enableSpeakerphone(bool? enable) => super.noSuchMethod(
    Invocation.method(#enableSpeakerphone, [enable]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i12.ByteBuffer> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i8.Future<_i12.ByteBuffer>.value(
              _i13.dummyValue<_i12.ByteBuffer>(
                this,
                Invocation.method(#captureFrame, []),
              ),
            ),
          )
          as _i8.Future<_i12.ByteBuffer>);

  @override
  _i8.Future<bool> hasTorch() =>
      (super.noSuchMethod(
            Invocation.method(#hasTorch, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setTorch(bool? torch) =>
      (super.noSuchMethod(
            Invocation.method(#setTorch, [torch]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [MediaStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStream extends _i1.Mock implements _i6.MediaStream {
  MockMediaStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get ownerTag =>
      (super.noSuchMethod(
            Invocation.getter(#ownerTag),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#ownerTag),
            ),
          )
          as String);

  @override
  set onAddTrack(dynamic Function(_i6.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAddTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoveTrack(dynamic Function(_i6.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoveTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> getMediaTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getMediaTracks, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addTrack(
    _i6.MediaStreamTrack? track, {
    bool? addToNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track], {#addToNative: addToNative}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTrack(
    _i6.MediaStreamTrack? track, {
    bool? removeFromNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeTrack,
              [track],
              {#removeFromNative: removeFromNative},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i6.MediaStreamTrack> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: <_i6.MediaStreamTrack>[],
          )
          as List<_i6.MediaStreamTrack>);

  @override
  List<_i6.MediaStreamTrack> getAudioTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioTracks, []),
            returnValue: <_i6.MediaStreamTrack>[],
          )
          as List<_i6.MediaStreamTrack>);

  @override
  List<_i6.MediaStreamTrack> getVideoTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoTracks, []),
            returnValue: <_i6.MediaStreamTrack>[],
          )
          as List<_i6.MediaStreamTrack>);

  @override
  _i6.MediaStreamTrack? getTrackById(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#getTrackById, [trackId]))
          as _i6.MediaStreamTrack?);

  @override
  _i8.Future<_i6.MediaStream> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i8.Future<_i6.MediaStream>.value(
              _FakeMediaStream_5(this, Invocation.method(#clone, [])),
            ),
          )
          as _i8.Future<_i6.MediaStream>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
